# Generated by Django 5.2.1 on 2025-05-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("date_time", models.DateTimeField()),
                (
                    "periodicity",
                    models.CharField(
                        choices=[
                            ("once", "Одноразова"),
                            ("daily", "Щоденна"),
                            ("weekly", "Щотижнева"),
                            ("monthly", "Щомісячна"),
                            ("yearly", "Щорічна"),
                        ],
                        default="once",
                        max_length=20,
                    ),
                ),
                ("reminder_minutes", models.IntegerField(default=10)),
                ("category", models.CharField(default="other", max_length=50)),
                ("tags", models.TextField(blank=True)),
            ],
        ),
    ]
