# Generated by Django 5.2.1 on 2025-05-23 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="notified",
            field=models.BooleanField(default=False),
        ),
    ]
