# Generated by Django 5.2.1 on 2025-05-27 15:10

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0003_event_notified"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="category",
            field=models.CharField(
                choices=[
                    ("work", "Work"),
                    ("study", "Study"),
                    ("personal", "Personal"),
                    ("health", "Health"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="reminder_minutes",
            field=models.IntegerField(
                default=10,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1440),
                ],
            ),
        ),
        migrations.AlterUniqueTogether(
            name="event",
            unique_together={("user", "name", "date_time")},
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["user", "date_time"], name="event_event_user_id_7d8e17_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["notified"], name="event_event_notifie_4f87b8_idx"
            ),
        ),
    ]
