# Generated by Django 5.2.1 on 2025-05-23 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="language",
            field=models.CharField(default="ua", max_length=5),
        ),
    ]
